### ISSUE TITLE
load existing GLMsingle betas in example scripts, if they already exist on disk?

### ISSUE THREAD

**Issue by jacob-prince** [kendrickkay/GLMsingle#13]
problem: if a user wants to re-run any of the example scripts, they must again wait 5-15(?) minutes for the entire run of GLMsingle to complete on our example datasets. this becomes pretty inconvenient for anyone who wants to revisit the example scripts more than once. 

proposed solution: 
- add level of folder hierarchy within ~/examples/$dataset/ with one folder containing outputs from "optimizedGLM" and one containing outputs from "baselineGLM"
- set opt.wantmemoryoutputs to [1 1 0 0] for the baselineGLM and [1 1 1 1] for the optimizedGLM, and make the fourth argument to GLMsingle point to the above subdirectories
- before any run of GLMsingle, check if the relevant output files exist; load them if so, else run GLMsingle again
- proceed with reliability calculations as usual

**Comment by kendrickkay** [comment]
hmm...   in my opinion, this is a bit overthinking the example scripts.  or at least, lower priority than other things :)     a simple "fix" is to simply have a line where the example script saves the result to disk and maybe a commented-out line that shows how you could load the results from disk instead of re-running.

**Comment by jacob-prince** [comment]
fair enough, seems like a good compromise

**Comment by jacob-prince** [comment]
closing this issue, as this feature has been implemented in the latest versions of the matlab and python example scripts.
